name: iOS Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Build Archive
        run: xcodebuild archive -project ZAnime.xcodeproj -scheme ZAnime -archivePath ZAnime.xcarchive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath ZAnime.xcarchive -exportPath output -exportOptionsPlist ZAnime/ExportOptions.plist CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4   # <-- تم التحديث من v3 إلى v4
        with:
          name: ZAnime-IPA
          path: output/*.ipa